import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/layout/header";
import AuthGuard from "./components/auth/AuthGuard";
import Footer from "./components/layout/footer";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Student Management Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppRouterCacheProvider options={{ key: "mui" }}>
          <Header />
          <AuthGuard>{children}</AuthGuard>
          <Footer />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
